services:
  strapi:
    image: k3n5h1n/strapi-blog:latest
    container_name: my-strapi-project
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - HOST=0.0.0.0
      - PORT=1337
      - NODE_ENV=production
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
    ports:
      - "1337:1337"
    volumes:
      - ./.tmp:/app/.tmp
      - ./public/uploads:/app/public/uploads
      - ./config:/app/config
    networks:
      - strapi-network
networks:
  strapi-network:
    driver: bridge
